package com.retina.ai.repository;
import com.retina.ai.model.*; import java.util.*; import java.util.concurrent.*;
public final class Repositories {
 public final Users users=new Users(); public final Analyses analyses=new Analyses(); public final Messages messages=new Messages(); public final Billing billing=new Billing();
 public static class Users { private final ConcurrentHashMap<String,AppUser> data=new ConcurrentHashMap<>(); public AppUser save(AppUser u){data.put(u.id,u);return u;} public Optional<AppUser> byId(String id){return Optional.ofNullable(data.get(id));} public Optional<AppUser> byEmail(String e){return data.values().stream().filter(u->u.email.equalsIgnoreCase(e)).findFirst();} public List<AppUser> all(){return List.copyOf(data.values());}}
 public static class Analyses { private final ConcurrentHashMap<String,RetinalAnalysis> data=new ConcurrentHashMap<>(); public RetinalAnalysis save(RetinalAnalysis a){data.put(a.id,a);return a;} public Optional<RetinalAnalysis> byId(String id){return Optional.ofNullable(data.get(id));} public List<RetinalAnalysis> byPatient(String p){return data.values().stream().filter(a->a.patientId.equals(p)).toList();} public List<RetinalAnalysis> all(){return List.copyOf(data.values());}}
 public static class Messages { private final CopyOnWriteArrayList<ChatMessage> data=new CopyOnWriteArrayList<>(); public ChatMessage save(ChatMessage m){data.add(m);return m;} public List<ChatMessage> conversation(String a,String b){return data.stream().filter(m->(m.senderId().equals(a)&&m.recipientId().equals(b))||(m.senderId().equals(b)&&m.recipientId().equals(a))).sorted(java.util.Comparator.comparing(ChatMessage::sentAt)).toList();}}
 public static class Billing { private final ConcurrentHashMap<String,Subscription> subs=new ConcurrentHashMap<>(); private final CopyOnWriteArrayList<PaymentRecord> pays=new CopyOnWriteArrayList<>(); public Subscription save(Subscription s){subs.put(s.userId,s);return s;} public Optional<Subscription> sub(String u){return Optional.ofNullable(subs.get(u));} public PaymentRecord pay(PaymentRecord p){pays.add(p);return p;} public List<PaymentRecord> pays(String u){return pays.stream().filter(p->p.userId().equals(u)).toList();}}
}
