package com.retina.ai.service;
import com.retina.ai.dto.*; import com.retina.ai.model.*; import com.retina.ai.repository.Repositories; import java.math.BigDecimal; import java.nio.charset.StandardCharsets; import java.security.*; import java.time.*; import java.util.*;
public class PlatformService {
 private final Repositories repo; private final OpenAiVisionService openAi; public PlatformService(Repositories repo, OpenAiVisionService openAi){this.repo=repo;this.openAi=openAi;}
 public Responses.Auth register(Requests.Register r){repo.users.byEmail(r.email()).ifPresent(u->{throw new IllegalArgumentException("Email already registered");}); Set<Role> roles=r.roles()==null||r.roles().isEmpty()?EnumSet.of(Role.USER):r.roles(); AppUser u=new AppUser(UUID.randomUUID().toString(),r.email(),hash(r.password()),"email",roles); u.profile.fullName=r.fullName(); repo.users.save(u); return auth(u);} 
 public Responses.Auth login(Requests.Login r){AppUser u=repo.users.byEmail(r.email()).orElseThrow(()->new IllegalArgumentException("Invalid credentials")); if(!u.passwordHash.equals(hash(r.password()))) throw new IllegalArgumentException("Invalid credentials"); return auth(u);} 
 public Responses.Auth socialLogin(Requests.SocialLogin r){AppUser u=repo.users.byEmail(r.email()).orElseGet(()->{AppUser n=new AppUser(UUID.randomUUID().toString(),r.email(),"social",r.provider(),EnumSet.of(Role.USER)); n.profile.fullName=r.fullName(); return repo.users.save(n);}); return auth(u);} 
 public Responses.Analysis upload(Requests.UploadAnalysis r){RetinalAnalysis a=new RetinalAnalysis(UUID.randomUUID().toString(),r.patientId()); a.status=AnalysisStatus.PROCESSING; long total=0; for(Requests.ImageInput i:r.images()){total+=i.sizeBytes(); a.images.add(new AnalysisImage(i.fileName(),i.contentType(),i.sizeBytes(),r.imageType()));} a.findings=findings(a.images,total); a.riskScore=Math.min(.98,.18+a.findings.size()*.17+(total%1000)/5000.0); a.riskLevel=classify(a.riskScore); var decision=openAi.analyze(a.images,a.findings,a.riskScore,a.riskLevel); a.aiConclusion=decision.conclusion(); a.recommendation=decision.recommendation(); a.annotatedImageUrl="/api/user/analyses/"+a.id+"/annotated-image.svg"; a.status=AnalysisStatus.READY; a.readyAt=Instant.now(); repo.analyses.save(a); repo.billing.sub(r.patientId()).ifPresent(Subscription::consumeOne); System.out.println("Notification: AI result ready for "+a.patientId+" analysis="+a.id); return toDto(a);} 
 public List<Responses.Analysis> history(String patientId){return repo.analyses.byPatient(patientId).stream().sorted(Comparator.comparing((RetinalAnalysis a)->a.createdAt).reversed()).map(this::toDto).toList();}
 public RetinalAnalysis analysis(String id){return repo.analyses.byId(id).orElseThrow(()->new IllegalArgumentException("Analysis not found"));}
 public Responses.Analysis review(String doctorId,String analysisId,Requests.DoctorReview r){RetinalAnalysis a=analysis(analysisId); a.doctorId=doctorId; a.doctorConclusion=r.conclusion(); a.doctorNotes=r.notes(); a.doctorConfirmed=r.confirmed(); if(r.adjustedRiskLevel()!=null)a.riskLevel=r.adjustedRiskLevel(); a.status=AnalysisStatus.REVIEWED; return toDto(repo.analyses.save(a));}
 public List<AppUser> patients(String doctorId,String query,RiskLevel risk){return repo.users.all().stream().filter(u->doctorId.equals(u.profile.assignedDoctorId)).filter(u->query==null||query.isBlank()||u.id.contains(query)||u.email.contains(query)||(u.profile.fullName!=null&&u.profile.fullName.toLowerCase().contains(query.toLowerCase()))).filter(u->risk==null||repo.analyses.byPatient(u.id).stream().anyMatch(a->a.riskLevel==risk)).toList();}
 public Responses.Performance performance(){var all=repo.analyses.all(); return new Responses.Performance(all.size(), all.stream().filter(a->a.doctorConfirmed).count(), all.stream().mapToDouble(a->a.riskScore).average().orElse(0), all.stream().filter(a->a.riskLevel==RiskLevel.HIGH||a.riskLevel==RiskLevel.CRITICAL).count());}
 public void feedback(Requests.AiFeedback r){System.out.println("AI feedback: "+r);} public ChatMessage send(Requests.SendMessage r){String t=r.senderId().compareTo(r.recipientId())<0?r.senderId()+":"+r.recipientId():r.recipientId()+":"+r.senderId(); return repo.messages.save(new ChatMessage(UUID.randomUUID().toString(),t,r.senderId(),r.recipientId(),r.body(),Instant.now()));}
 public List<ChatMessage> conversation(String a,String b){return repo.messages.conversation(a,b);} public Subscription purchase(String userId,Requests.Purchase r){Subscription s=new Subscription(userId,r.planName(),Math.max(1,r.analyses()),Instant.now().plus(Duration.ofDays(30))); repo.billing.save(s); repo.billing.pay(new PaymentRecord(UUID.randomUUID().toString(),userId,r.planName(),r.amount()==null? BigDecimal.ZERO:r.amount(),"PAID",Instant.now())); return s;} public Subscription subscription(String userId){return repo.billing.sub(userId).orElse(new Subscription(userId,"FREE",3,Instant.now().plus(Duration.ofDays(7))));} public List<PaymentRecord> payments(String userId){return repo.billing.pays(userId);} 
 public String csv(String id){RetinalAnalysis a=analysis(id); StringBuilder b=new StringBuilder("analysisId,patientId,riskLevel,riskScore,finding,severity,confidence,boundingBox\n"); for(AiFinding f:a.findings)b.append(a.id).append(',').append(a.patientId).append(',').append(a.riskLevel).append(',').append(a.riskScore).append(',').append(q(f.label())).append(',').append(f.severity()).append(',').append(f.confidence()).append(',').append(q(f.boundingBox())).append('\n'); return b.toString();}
 public byte[] pdf(String id){RetinalAnalysis a=analysis(id); return ("Retina AI Diagnostic Report\nAnalysis ID: "+a.id+"\nPatient ID: "+a.patientId+"\nRisk: "+a.riskLevel+"\nAI: "+a.aiConclusion+"\nRecommendation: "+a.recommendation+"\nDoctor: "+a.doctorConclusion+"\n").getBytes(StandardCharsets.UTF_8);} 
 private Responses.Auth auth(AppUser u){return new Responses.Auth("demo-"+u.id,u.id,u.email,u.roles);} private Responses.Analysis toDto(RetinalAnalysis a){return new Responses.Analysis(a.id,a.patientId,a.status,a.riskLevel,a.riskScore,a.images,a.findings,a.aiConclusion,a.recommendation,a.annotatedImageUrl,a.doctorConfirmed,a.doctorConclusion,a.doctorNotes,a.createdAt,a.readyAt);} private RiskLevel classify(double s){if(s>=.82)return RiskLevel.CRITICAL;if(s>=.62)return RiskLevel.HIGH;if(s>=.38)return RiskLevel.MODERATE;return RiskLevel.LOW;} private List<AiFinding> findings(List<AnalysisImage> images,long total){List<AiFinding> f=new ArrayList<>(); f.add(new AiFinding("Vessel narrowing","MODERATE",.78,"x=22,y=18,w=34,h=20","Vùng mạch máu co hẹp.")); if(images.size()>1||total%2==0)f.add(new AiFinding("Microaneurysm candidates","HIGH",.71,"x=55,y=42,w=18,h=16","Điểm nghi phình vi mạch.")); if(total%3==0)f.add(new AiFinding("Macular edema suspicion","HIGH",.64,"x=40,y=48,w=26,h=24","Nghi phù hoàng điểm.")); return f;} private String q(String v){return '"'+v.replace("\"","\"\"")+'"';} private String hash(String raw){try{byte[] d=MessageDigest.getInstance("SHA-256").digest(raw.getBytes(StandardCharsets.UTF_8));StringBuilder b=new StringBuilder();for(byte x:d)b.append(String.format("%02x",x));return b.toString();}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
}
